# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Build the TypeScript project
RUN npm run build

# Default command to start the MCP server over stdio
CMD ["node", "build/index.js"]
